/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'greenSmoothies' : IDL.Null,
  'classicShakes' : IDL.Null,
  'proteinShakes' : IDL.Null,
  'fruitSmoothies' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'emoji' : IDL.Text,
  'category' : Category,
  'basePrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'initializeMenu' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'greenSmoothies' : IDL.Null,
    'classicShakes' : IDL.Null,
    'proteinShakes' : IDL.Null,
    'fruitSmoothies' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'emoji' : IDL.Text,
    'category' : Category,
    'basePrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'initializeMenu' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };